/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotDotDotReactSrcRoutesToolsRouteImport } from './../../react/src/routes/tools'
import { Route as SecretsRouteImport } from './routes/app/secrets'
import { Route as DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport } from './../../react/src/routes/policies'
import { Route as DotDotDotDotDotDotReactSrcRoutesIndexRouteImport } from './../../react/src/routes/index'
import { Route as DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport } from './../../react/src/routes/resume.$executionId'
import { Route as DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../react/src/routes/integrations.$namespace'
import { Route as DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport } from './../../react/src/routes/plugins.$pluginId.$'
import { Route as DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../react/src/routes/integrations.add.$pluginKey'

const DotDotDotDotDotDotReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotReactSrcRoutesToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotReactSrcRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute =
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport.update({
    id: '/resume/$executionId',
    path: '/resume/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport.update({
    id: '/integrations/$namespace',
    path: '/integrations/$namespace',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute =
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport.update({
    id: '/plugins/$pluginId/$',
    path: '/plugins/$pluginId/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/integrations/add/$pluginKey',
      path: '/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesByTo {
  '/': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  '/policies': typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/tools': typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  '/plugins/$pluginId/$': typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  id:
    | '__root__'
    | '/'
    | '/policies'
    | '/secrets'
    | '/tools'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
    | '/plugins/$pluginId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotDotDotReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotReactSrcRoutesIndexRoute
  DotDotDotDotDotDotReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRoute
  SecretsRoute: typeof SecretsRoute
  DotDotDotDotDotDotReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolsRoute
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute: typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute: typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$executionId': {
      id: '/resume/$executionId'
      path: '/resume/$executionId'
      fullPath: '/resume/$executionId'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$namespace': {
      id: '/integrations/$namespace'
      path: '/integrations/$namespace'
      fullPath: '/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/$': {
      id: '/plugins/$pluginId/$'
      path: '/plugins/$pluginId/$'
      fullPath: '/plugins/$pluginId/$'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/add/$pluginKey': {
      id: '/integrations/add/$pluginKey'
      path: '/integrations/add/$pluginKey'
      fullPath: '/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotDotDotReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotReactSrcRoutesIndexRoute,
  DotDotDotDotDotDotReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotReactSrcRoutesPoliciesRoute,
  SecretsRoute: SecretsRoute,
  DotDotDotDotDotDotReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotReactSrcRoutesToolsRoute,
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotReactSrcRoutesIntegrationsDotnamespaceRoute,
  DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute:
    DotDotDotDotDotDotReactSrcRoutesResumeDotexecutionIdRoute,
  DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
  DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute:
    DotDotDotDotDotDotReactSrcRoutesPluginsDotpluginIdDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
