export {
  MICROSOFT_AUTHORIZATION_URL,
  MICROSOFT_AUTH_TEMPLATE_SLUG,
  MICROSOFT_GRAPH_BASE_SCOPES,
  MICROSOFT_GRAPH_BASE_URL,
  MICROSOFT_GRAPH_DEFAULT_PRESET_IDS,
  MICROSOFT_GRAPH_OPENAPI_URL,
  MICROSOFT_GRAPH_PRESET_ID,
  MICROSOFT_TOKEN_URL,
  microsoftGraphExactPathsForPresetIds,
  microsoftGraphPathPrefixesForPresetIds,
  microsoftGraphPreset,
  microsoftGraphPresetForId,
  microsoftGraphScopePresets,
  microsoftGraphScopesForPresetIds,
  type MicrosoftGraphPreset,
  type MicrosoftGraphScopeAudience,
  type MicrosoftGraphScopePreset,
} from "./presets";
export {
  buildMicrosoftGraphOpenApiSpec,
  decodeMicrosoftGraphIntegrationConfig,
  fetchMicrosoftGraphOpenApiSpec,
  filterMicrosoftGraphOpenApiSpec,
  type MicrosoftGraphIntegrationConfig,
  type MicrosoftGraphSelectionInput,
  type MicrosoftGraphSpecBuild,
} from "./graph";
export {
  microsoftPlugin,
  type MicrosoftConfigureInput,
  type MicrosoftGraphConfig,
  type MicrosoftPluginExtension,
  type MicrosoftPluginOptions,
  type MicrosoftUpdateInput,
  type MicrosoftUpdateResult,
} from "./plugin";
