export {
  MICROSOFT_AUTHORIZATION_URL,
  MICROSOFT_AUTH_TEMPLATE_SLUG,
  MICROSOFT_CLIENT_CREDENTIALS_AUTH_TEMPLATE_SLUG,
  MICROSOFT_GRAPH_ALL_PRESET_IDS,
  MICROSOFT_GRAPH_BASE_SCOPES,
  MICROSOFT_GRAPH_BASE_URL,
  MICROSOFT_GRAPH_CLIENT_CREDENTIALS_SCOPES,
  MICROSOFT_GRAPH_DEFAULT_SCOPE,
  MICROSOFT_GRAPH_DELEGATED_DEFAULT_SCOPES,
  MICROSOFT_GRAPH_DEFAULT_PRESET_IDS,
  MICROSOFT_GRAPH_OPENAPI_URL,
  MICROSOFT_GRAPH_PERMISSIONS_REFERENCE_URL,
  MICROSOFT_GRAPH_PRESET_ID,
  MICROSOFT_TOKEN_URL,
  microsoftGraphExactPathsForPresetIds,
  microsoftGraphPathPrefixesForPresetIds,
  microsoftGraphPreset,
  microsoftGraphPresetForId,
  microsoftGraphPresetIdsCoverFullGraph,
  microsoftGraphScopePresets,
  microsoftGraphScopesForPresetIds,
  microsoftGraphTagPrefixesForPresetIds,
  microsoftServiceSlug,
  type MicrosoftGraphPreset,
  type MicrosoftGraphScopeAudience,
  type MicrosoftGraphScopePreset,
} from "./presets";
export {
  buildMicrosoftGraphOpenApiSpec,
  decodeMicrosoftGraphIntegrationConfig,
  fetchMicrosoftGraphOpenApiSpec,
  fetchMicrosoftGraphPermissionsReference,
  microsoftGraphKeepPathItem,
  parseMicrosoftGraphDelegatedScopes,
  type MicrosoftGraphIntegrationConfig,
  type MicrosoftGraphSelectionInput,
  type MicrosoftGraphSpecBuild,
} from "./graph";
export {
  microsoftPlugin,
  type MicrosoftAddWorkloadsAdded,
  type MicrosoftAddWorkloadsFailed,
  type MicrosoftAddWorkloadsInput,
  type MicrosoftAddWorkloadsResult,
  type MicrosoftAddWorkloadsSkipped,
  type MicrosoftConfigureInput,
  type MicrosoftCustomWorkloadConfig,
  MICROSOFT_CUSTOM_WORKLOAD_ID,
  type MicrosoftPluginExtension,
  type MicrosoftPluginOptions,
  type MicrosoftPresetWorkloadConfig,
  type MicrosoftUpdateInput,
  type MicrosoftUpdateResult,
  type MicrosoftWorkloadConfig,
} from "./plugin";
