/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport } from './../../../packages/react/src/routes/tools'
import { Route as SetupMcpRouteImport } from './routes/app/setup-mcp'
import { Route as SecretsRouteImport } from './routes/app/secrets'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport } from './../../../packages/react/src/routes/policies'
import { Route as OrgRouteImport } from './routes/app/org'
import { Route as CreateOrgRouteImport } from './routes/app/create-org'
import { Route as BillingRouteImport } from './routes/app/billing'
import { Route as ApiKeysRouteImport } from './routes/app/api-keys'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport } from './../../../packages/react/src/routes/index'
import { Route as ResumeDotexecutionIdRouteImport } from './routes/app/resume.$executionId'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport } from './../../../packages/react/src/routes/integrations.$namespace'
import { Route as Billing_DotplansRouteImport } from './routes/app/billing_.plans'
import { Route as DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport } from './../../../packages/react/src/routes/integrations.add.$pluginKey'

const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const SetupMcpRoute = SetupMcpRouteImport.update({
  id: '/setup-mcp',
  path: '/setup-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResumeDotexecutionIdRoute = ResumeDotexecutionIdRouteImport.update({
  id: '/resume/$executionId',
  path: '/resume/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport.update(
    {
      id: '/integrations/$namespace',
      path: '/integrations/$namespace',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Billing_DotplansRoute = Billing_DotplansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute =
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport.update(
    {
      id: '/integrations/add/$pluginKey',
      path: '/integrations/add/$pluginKey',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/billing/plans': typeof Billing_DotplansRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/billing/plans': typeof Billing_DotplansRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  '/billing_/plans': typeof Billing_DotplansRoute
  '/integrations/$namespace': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  '/resume/$executionId': typeof ResumeDotexecutionIdRoute
  '/integrations/add/$pluginKey': typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/billing'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing_/plans'
    | '/integrations/$namespace'
    | '/resume/$executionId'
    | '/integrations/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRoute
  CreateOrgRoute: typeof CreateOrgRoute
  OrgRoute: typeof OrgRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute
  SecretsRoute: typeof SecretsRoute
  SetupMcpRoute: typeof SetupMcpRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute
  Billing_DotplansRoute: typeof Billing_DotplansRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute
  ResumeDotexecutionIdRoute: typeof ResumeDotexecutionIdRoute
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-mcp': {
      id: '/setup-mcp'
      path: '/setup-mcp'
      fullPath: '/setup-mcp'
      preLoaderRoute: typeof SetupMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$executionId': {
      id: '/resume/$executionId'
      path: '/resume/$executionId'
      fullPath: '/resume/$executionId'
      preLoaderRoute: typeof ResumeDotexecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$namespace': {
      id: '/integrations/$namespace'
      path: '/integrations/$namespace'
      fullPath: '/integrations/$namespace'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/plans': {
      id: '/billing_/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof Billing_DotplansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/add/$pluginKey': {
      id: '/integrations/add/$pluginKey'
      path: '/integrations/add/$pluginKey'
      fullPath: '/integrations/add/$pluginKey'
      preLoaderRoute: typeof DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRoute,
  CreateOrgRoute: CreateOrgRoute,
  OrgRoute: OrgRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesPoliciesRoute,
  SecretsRoute: SecretsRoute,
  SetupMcpRoute: SetupMcpRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesToolsRoute,
  Billing_DotplansRoute: Billing_DotplansRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotnamespaceRoute,
  ResumeDotexecutionIdRoute: ResumeDotexecutionIdRoute,
  DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute:
    DotDotDotDotDotDotDotDotPackagesReactSrcRoutesIntegrationsDotaddDotpluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
